rspack-contrib/rstack-examples

rspack/express/package.json

It was throwing an error
> rspack build
Rspack compiled successfully in 94 ms
/Users/bytedance/github/rspack-examples/rspack/express/dist/main.js:15276 } else throw new Error("[HMR] Hot Module Replacement is disabled.");
^
Error: [HMR] Hot Module Replacement is disabled.
at 5302 (/Users/bytedance/github/rspack-examples/rspack/express/dist/main.js:15276:14)

fix(rspack/express): fix the build command

---

libs/lib3/package.json
libs/lib3/src/index.js
rspack/builtin-swc-loader/package.json
rspack/builtin-swc-loader/rspack.config.js
rspack/builtin-swc-loader/src/index.jsx
rspack/nest-alias/rspack.config.js

builtin:swc-loader will inject @swc/helpers into transformed code which will cause phantom deps, so it would better to configure alias for @swc/helpers for monorepo

chore: add swc helpers alias in monorepo

---

rsbuild/express/.gitignore
rsbuild/express/README.md
rsbuild/express/package.json
rsbuild/express/rsbuild.config.mjs
rsbuild/express/server.mjs
rsbuild/express/src/index.css
rsbuild/express/src/index.js

Rsbuild's createDevServer method can be used to integrate the Rsbuild dev-server into a custom server.
https://rsbuild.dev/api/javascript-api/instance#rsbuildcreatedevserver

feat: add rsbuild with express example

---

rspack/treeshaking-transform-imports/package.json
rspack/treeshaking-transform-imports/rspack.config.js
rspack/treeshaking-transform-imports/src/a.js
rspack/treeshaking-transform-imports/src/b.js
rspack/treeshaking-transform-imports/src/c.js
rspack/treeshaking-transform-imports/src/index.js
rspack/treeshaking-transform-imports/src/sdk.js

This example shows how `optimization.sideEffects` transforms imports, and how to solve the circular dependencies issue

feat: add treeshaking transform imports example

---

rspack/basic-ts-config/package.json
rspack/basic-ts/package.json
rspack/basic/package.json
rspack/emotion/package.json
rspack/eslint/package.json
rspack/express/package.json
rspack/extract-license/package.json
rspack/library/package.json
rspack/nestjs/package.json
rspack/node-globals-shim/package.json
rspack/node-polyfill/package.json
rspack/perfsee/package.json
rspack/polyfill/package.json
rspack/postcss-loader/package.json
rspack/stats/package.json
rspack/styled-components/package.json
rspack/tailwind-jit/package.json
rspack/tailwind/package.json
rspack/worklet/package.json

otherwise the treeshaking feature will drop css imports.
closes: https://github.com/web-infra-dev/rspack/issues/6240

chore: add styles into sideEffects field in package.json

---

rspack/vanilla-extract-css/package.json

Closes #5
That error is related to nmf hooks that has been shipped in 0.6.x.
So it now works.

chore: enable rspack build in rspack/vanilla-extract-css

---

rsbuild/emotion/package.json
rsbuild/emotion/rsbuild.config.ts
rspack/emotion/package.json
rspack/emotion/rspack.config.js

Use `@swc/plugin-emotion` to replace `rspackExperiments.emotion`.

feat: use @swc/plugin-emotion

---

pnpm-lock.yaml
rspack/lightingcss-loader/index.html
rspack/lightingcss-loader/package.json
rspack/lightingcss-loader/rspack.config.js
rspack/lightingcss-loader/src/answer.css
rspack/lightingcss-loader/src/answer.js
rspack/lightingcss-loader/src/index.css
rspack/lightingcss-loader/src/index.js

add builtin:lightningcss-loader example for both `type:css` and `type:javascript/auto`

chore: add builtin:lightningcss-loader example

---

pnpm-lock.yaml
rspack/extract-license/package.json

don't know why the build is disabled before, but it seems it can build successfully so enable it

fix: enable extract-license build

---

pnpm-workspace.yaml

pnpm workspace should exclude the dist folder

fix: pnpm workspace exclude dist folder

---

rsbuild/express/server.mjs
rsbuild/ssr-express/server.mjs

fix: https://github.com/rspack-contrib/rspack-examples/issues/142
Typing error in express example.
https://typescript-eslint.io/rules/no-misused-promises/

fix: express afterListen typo

---

rsbuild/module-federation-enhanced/consumer/rsbuild.config.ts
rsbuild/module-federation-enhanced/provider/rsbuild.config.ts
rsbuild/module-federation/host/rsbuild.config.ts
rsbuild/module-federation/remote/rsbuild.config.ts

Disable the react plugin auto chunking strategy in the react example to see the benefits of the module federation sharing option that is configured.
This should be done, otherwise the example does configure a sharing strategy that never has an effect within the federation.

fix: disable Rsbuild react plugin chunking strategy for federation examples

---

rspack/nestjs/rspack.config.js

This PR updates the Nest.js example to include minimizer options. The minimization was previously disabled, however it's possible to enable this with the right settings to allow for optimized production builds.
The main issue when using Nest.js is the [ExecutionContext](https://docs.nestjs.com/fundamentals/execution-context#executioncontext-class) implementation, which retrieves class and handler values based on function names. This causes issues, for example when using this in combination with [decorator metadata](https://docs.nestjs.com/fundamentals/execution-context#reflection-and-metadata).

chore: update Nestjs example to include minimizer options

---

pnpm-lock.yaml
rsbuild/ssr-express-with-manifest/.gitignore
rsbuild/ssr-express-with-manifest/README.md
rsbuild/ssr-express-with-manifest/package.json
rsbuild/ssr-express-with-manifest/prod-server.mjs
rsbuild/ssr-express-with-manifest/rsbuild.config.mjs
rsbuild/ssr-express-with-manifest/server.mjs
rsbuild/ssr-express-with-manifest/src/App.css
rsbuild/ssr-express-with-manifest/src/App.tsx
rsbuild/ssr-express-with-manifest/src/env.d.ts
rsbuild/ssr-express-with-manifest/src/index.server.tsx
rsbuild/ssr-express-with-manifest/src/index.tsx
rsbuild/ssr-express-with-manifest/template.html
rsbuild/ssr-express-with-manifest/tsconfig.json

In some cases, the user's html is provided on the server side, and the manifest of script and link needs to be obtained and injected into the html. Grouped manifests can be easily obtained using the [output.manifest](https://rsbuild.dev/config/output/manifest) configuration.
```ts
const { entries } = JSON.parse(fs.readFileSync('./dist/manifest.json', 'utf-8'));
const { js, css } = entries['index'].initial;
const scriptTags = js.map(file => `<script src="${file}" defer></script>`).join('\n');
const styleTags = css.map(file => `<link rel="stylesheet" href="${file}">`).join('\n');  
const html = templateHtml.replace('', `${scriptTags}\n${styleTags}`);
```

feat: add Rsbuild SSR express with manifest example

---

rsbuild/ssr-express-with-manifest/rsbuild.config.mjs
rsbuild/ssr-express-with-manifest/server.mjs

Starting with rsbuild 1.1.7, manifest is always write to disk, `writeToDisk` is not required.

chore: enhance ssr manifest example

---

.github/renovate.json5

let renovate bump all non-major dependencies

chore: let renovate bump all non-major dependencies

---

pnpm-lock.yaml
rspack/basic-ts-config/package.json

Fix https://github.com/web-infra-dev/rspack/actions/runs/12646686870/job/35238282060

fix: missing typescript dep in basic-ts-config

---

pnpm-lock.yaml
rsbuild/query-raw/.gitignore
rsbuild/query-raw/README.md
rsbuild/query-raw/package.json
rsbuild/query-raw/rsbuild.config.ts
rsbuild/query-raw/src/App.css
rsbuild/query-raw/src/App.tsx
rsbuild/query-raw/src/env.d.ts
rsbuild/query-raw/src/index.tsx
rsbuild/query-raw/tsconfig.json

Add Rsbuild import asset as string example, supports importing assets as string via `?raw` suffix.
```ts
import cssStr from './App.css?raw';
import jsonStr from '../package.json?raw';
console.log('cssStr', cssStr); // output raw string
console.log('jsonStr', jsonStr);  // output raw string
```
More context: https://github.com/web-infra-dev/rsbuild/issues/3435

feat: add rsbuild import asset as string example

---

rsbuild/vanilla-extract/rsbuild.config.ts

Fixes example missing exclude `node_modules` in react refresh options which causes in my app error in dev mode (in production build everyting is fine)
```
drune@MBA my-rsbuild-app % npm run dev
> my-rsbuild-app@1.0.0 dev
> rsbuild dev --open
Rsbuild v1.2.11
➜ Local:    http://localhost:3000/
➜ Network:  http://192.168.1.64:3000/
➜ press h + enter to show shortcuts
start   Building...
/Users/drune/Developer/github.com/AdmiralDS/my-rsbuild-app/src/components/Button/button.css.ts:60
var maybeModule = __webpack_require__.c[moduleId];
^
TypeError: Cannot read properties of undefined (reading './node_modules/@admiral-ds/web/dist/chunks/vars.css-DQNm5B2I.js')
at Object.getModuleExports (/Users/drune/Developer/github.com/AdmiralDS/my-rsbuild-app/src/components/Button/button.css.ts:60:42)
at …
```

fix: reactRefreshOptions exclude must contain node_modules

---

rspack/lightingcss-loader/rspack.config.js

Should not use `experiments.css` and `css-extract` the same time. It would create the same css chunk with the same name and this is an error for emitting files.

fix: lightningcss-loader should not receive js comments

---

package.json

- Use `exit 0` instead of Unix `true` command to suppress errors

fix(scripts): resolve Windows compatibility issue in husky prepare script

---

README.md

This pull request updates the `README.md` file to improve documentation for cloning examples and fixes a formatting issue in the examples table. Below are the key changes:
* Added a new section, "Clone single example," to explain how to use the `gitpick` tool for cloning specific sub-directories from the repository. This includes a step-by-step example for cloning the `/rspack/basic` example.
* Added a "Clone all examples" section to clarify the steps for cloning the entire repository.
* Fixed alignment issues in the examples table by updating column formatting for better readability.

docs: update README with gitpick example

---

pnpm-lock.yaml
rspack/css-chunking-plugin/index.html
rspack/css-chunking-plugin/package.json
rspack/css-chunking-plugin/rspack.config.js
rspack/css-chunking-plugin/src/index.js
rspack/css-chunking-plugin/src/page.js
rspack/css-chunking-plugin/src/styles/component.css
rspack/css-chunking-plugin/src/styles/global.css
rspack/css-chunking-plugin/src/styles/theme.css

feat: css chunking plugin demo

feat: add css chunking plugin demo

---

pnpm-lock.yaml
rspack/library-esm/rspack.config.mjs
rspack/react-refresh-esm/index.html
rspack/react-refresh-esm/package.json
rspack/react-refresh-esm/rspack.config.js
rspack/react-refresh-esm/src/App.tsx
rspack/react-refresh-esm/src/ArrowFunction.tsx
rspack/react-refresh-esm/src/ClassDefault.tsx
rspack/react-refresh-esm/src/ClassNamed.tsx
rspack/react-refresh-esm/src/FunctionDefault.tsx
rspack/react-refresh-esm/src/FunctionNamed.tsx
rspack/react-refresh-esm/src/LazyComponent.tsx
rspack/react-refresh-esm/src/index.tsx

add an ESM output configured React application example.

feat: add ESM application example

---

.vscode/settings.json
pnpm-lock.yaml
rsbuild/ssr-express-with-manifest/package.json
rsbuild/ssr-express-with-manifest/rsbuild.config.mjs
rsbuild/ssr-express-with-manifest/server.mjs
rsbuild/ssr-express/package.json
rsbuild/ssr-express/rsbuild.config.mjs
rsbuild/ssr-express/server.mjs
rsbuild/ssr/package.json
rsbuild/ssr/rsbuild.config.ts

Enable ESM for the Rsbuild SSR examples via `output.module: true`.

feat(rsbuild): enable ESM for SSR examples

---

pnpm-lock.yaml
rsbuild/react-jest/package.json
rsbuild/react-rstest/package.json
rspack/basic-ts-config/package.json
rspack/basic-ts-config/tsconfig.json

ts-node is no longer required since `@rspack/cli` >= 1.5.0
See: https://github.com/web-infra-dev/rspack/releases/tag/v1.5.0

chore: remove ts-node dependency and related config
