rspack-contrib/rstack-examples

- rspack/basic-mts-config/index.html
- rspack/basic-mts-config/package.json
- rspack/basic-mts-config/rspack.config.mts
- rspack/basic-mts-config/src/answer.js
- rspack/basic-mts-config/src/index.js
- rspack/basic-mts-config/tsconfig.json
- rspack/basic-ts-config/index.html
- rspack/basic-ts-config/package.json
- rspack/basic-ts-config/rspack.config.ts
- rspack/basic-ts-config/src/answer.js
- rspack/basic-ts-config/src/index.js
- rspack/basic/rspack.config.js
add ts and mts config for reference
> chore: add ts config example

- rsdoctor/arco-pro/rspack.config.js
> fix(rsdoctor): change loader config

- pnpm-workspace.yaml
- rsbuild/react/package.json
- rspress/basic/package.json
- tsconfig.base.json
- update rsbuild v0.4
- remove empty modern.js folder
> chore: update rsbuild v0.4

- rsbuild/react-jest/.gitignore
- rsbuild/react-jest/README.md
- rsbuild/react-jest/jest-setup.ts
- rsbuild/react-jest/jest.config.ts
- rsbuild/react-jest/package.json
- rsbuild/react-jest/rsbuild.config.ts
- rsbuild/react-jest/src/App.css
- rsbuild/react-jest/src/App.tsx
- rsbuild/react-jest/src/env.d.ts
- rsbuild/react-jest/src/index.tsx
- rsbuild/react-jest/tests/App.spec.tsx
- rsbuild/react-jest/tests/__mocks__/fileMock.js
- rsbuild/react-jest/tests/__mocks__/styleMock.js
- rsbuild/react-jest/tests/tsconfig.json
- rsbuild/react-jest/tsconfig.json
Add rsbuild-react-jest example.
> feat: add rsbuild-react-jest example

- rsbuild/lit/package.json
- rsbuild/module-federation/host/package.json
- rsbuild/module-federation/remote/package.json
- rsbuild/preact/package.json
- rsbuild/react-eslint/package.json
- rsbuild/react-jest/package.json
- rsbuild/react-mdx/package.json
- rsbuild/react/package.json
- rsbuild/solid/package.json
- rsbuild/svelte/package.json
- rsbuild/vue2/package.json
- rsbuild/vue3-auto-import/package.json
- rsbuild/vue3-eslint/package.json
- rsbuild/vue3-vant/package.json
- rsbuild/vue3/package.json
https://rsbuild.dev/community/releases/v0-5
> chore: bump Rsbuild v0.5

- rsbuild/react-tailwindcss/.gitignore
- rsbuild/react-tailwindcss/README.md
- rsbuild/react-tailwindcss/package.json
- rsbuild/react-tailwindcss/postcss.config.ts
- rsbuild/react-tailwindcss/rsbuild.config.ts
- rsbuild/react-tailwindcss/src/App.css
- rsbuild/react-tailwindcss/src/App.tsx
- rsbuild/react-tailwindcss/src/env.d.ts
- rsbuild/react-tailwindcss/src/index.tsx
- rsbuild/react-tailwindcss/tailwind.config.ts
- rsbuild/react-tailwindcss/tsconfig.json
Add rsbuild-react-tailwindcss example
> Add rsbuild-react-tailwindcss example

- rsbuild/react-tailwindcss-v4/.gitignore
- rsbuild/react-tailwindcss-v4/README.md
- rsbuild/react-tailwindcss-v4/package.json
- rsbuild/react-tailwindcss-v4/postcss.config.ts
- rsbuild/react-tailwindcss-v4/rsbuild.config.ts
- rsbuild/react-tailwindcss-v4/src/App.css
- rsbuild/react-tailwindcss-v4/src/App.tsx
- rsbuild/react-tailwindcss-v4/src/env.d.ts
- rsbuild/react-tailwindcss-v4/src/index.tsx
- rsbuild/react-tailwindcss-v4/tsconfig.json
https://tailwindcss.com/blog/tailwindcss-v4-alpha
> Add rsbuild-react-tailwindcss-v4 example

- rspack/builtin-swc-loader/package.json
- rspack/react-storybook/.storybook/main.js
- rspack/react-storybook/.storybook/rspack.config.js
- rspack/react-storybook/README.md
- rspack/react-storybook/modern.config.ts
- rspack/react-storybook/package.json
- rspack/react-storybook/src/stories/Button.stories.js
- rspack/react-storybook/tsconfig.json
supersede storybook-react-rspack by @modern-js/storybook.
> feat(storybook): use @modern-js/storybook

- rspack/worker/example.js
- rspack/worker/package.json
thanks @kingwl for this suggestion
> chore: add load worker from cross origin example

- rsbuild/lit/package.json
- rsbuild/module-federation/host/package.json
- rsbuild/module-federation/remote/package.json
- rsbuild/preact/package.json
- rsbuild/react-eslint/package.json
- rsbuild/react-jest/package.json
- rsbuild/react-lightningcss/package.json
- rsbuild/react-mdx/package.json
- rsbuild/react-tailwindcss-v4/package.json
- rsbuild/react-tailwindcss/package.json
- rsbuild/react/package.json
- rsbuild/solid/package.json
- rsbuild/svelte/package.json
- rsbuild/vue2/package.json
- rsbuild/vue3-auto-import/package.json
- rsbuild/vue3-eslint/package.json
- rsbuild/vue3-vant/package.json
- rsbuild/vue3/package.json
https://github.com/web-infra-dev/rsbuild/releases/tag/v0.6.0
> feat: bump Rsbuild v0.6

- rspack/react-with-extract-css/index.html
- rspack/react-with-extract-css/package.json
- rspack/react-with-extract-css/rspack.config.js
- rspack/react-with-extract-css/src/components/hello-world.jsx
- rspack/react-with-extract-css/src/components/index.module.less
- rspack/react-with-extract-css/src/index.jsx
- rspack/react-with-extract-css/src/style/themes/default.less
- rspack/react-with-extract-css/src/style/themes/index.less
- rspack/react-with-extract-css/src/styles.less
Add CssExtractRspackPlugin example
> feat: update css-extract example

- rsbuild/fastify/.gitignore
- rsbuild/fastify/README.md
- rsbuild/fastify/package.json
- rsbuild/fastify/rsbuild.config.mjs
- rsbuild/fastify/server.mjs
- rsbuild/fastify/src/index.css
- rsbuild/fastify/src/index.js
add rsbuild fastify example. using [rsbuild#createdevserver](https://rsbuild.dev/api/javascript-api/instance#rsbuildcreatedevserver) api
> feat: add rsbuild fastify example

- package.json
For more details, refer to: https://github.com/theKashey/react-focus-lock/issues/301
> fix: latest fix-react-focus-lock breaks webpack build

- rsbuild/react-19/.gitignore
- rsbuild/react-19/README.md
- rsbuild/react-19/package.json
- rsbuild/react-19/rsbuild.config.ts
- rsbuild/react-19/src/App.css
- rsbuild/react-19/src/App.tsx
- rsbuild/react-19/src/env.d.ts
- rsbuild/react-19/src/index.tsx
- rsbuild/react-19/tsconfig.json
Add rsbuild-react-19 example to test React 19 Beta
> Add rsbuild-react-19 example

- rsbuild/vanilla-extract/.gitignore
- rsbuild/vanilla-extract/README.md
- rsbuild/vanilla-extract/package.json
- rsbuild/vanilla-extract/rsbuild.config.ts
- rsbuild/vanilla-extract/src/App.css.ts
- rsbuild/vanilla-extract/src/App.tsx
- rsbuild/vanilla-extract/src/env.d.ts
- rsbuild/vanilla-extract/src/index.css
- rsbuild/vanilla-extract/src/index.tsx
- rsbuild/vanilla-extract/tsconfig.json
https://github.com/web-infra-dev/rsbuild/discussions/2298
> feat: add rsbuild-vanilla-extract example

- rsbuild/styled-components/.gitignore
- rsbuild/styled-components/README.md
- rsbuild/styled-components/package.json
- rsbuild/styled-components/rsbuild.config.ts
- rsbuild/styled-components/src/App.tsx
- rsbuild/styled-components/src/env.d.ts
- rsbuild/styled-components/src/index.tsx
- rsbuild/styled-components/tsconfig.json
Add rsbuild-styled-components example
> feat: add rsbuild-styled-components example

- rsbuild/emotion/.gitignore
- rsbuild/emotion/README.md
- rsbuild/emotion/package.json
- rsbuild/emotion/rsbuild.config.ts
- rsbuild/emotion/src/App.tsx
- rsbuild/emotion/src/env.d.ts
- rsbuild/emotion/src/index.tsx
- rsbuild/emotion/tsconfig.json
> feat: add rsbuild-emotion example

- rsbuild/stylex/.gitignore
- rsbuild/stylex/README.md
- rsbuild/stylex/package.json
- rsbuild/stylex/rsbuild.config.ts
- rsbuild/stylex/src/App.tsx
- rsbuild/stylex/src/env.d.ts
- rsbuild/stylex/src/index.css
- rsbuild/stylex/src/index.tsx
- rsbuild/stylex/tsconfig.json
use https://github.com/eryue0220/unplugin-stylex
> feat: add rsbuild-stylex example

- rspress/custom-theme/.gitignore
- rspress/custom-theme/docs/hello.md
- rspress/custom-theme/docs/index.md
- rspress/custom-theme/package-lock.json
- rspress/custom-theme/package.json
- rspress/custom-theme/rspress.config.ts
- rspress/custom-theme/theme/index.tsx
- rspress/custom-theme/tsconfig.json
related:
- https://discord.com/channels/977448667919286283/1161653869080756245/1211514417091575879
- https://github.com/web-infra-dev/rspress/discussions/1045
> feat(rspress): add example of custom theme

- .gitignore
- rsbuild/styled-jsx/.gitignore
- rsbuild/styled-jsx/README.md
- rsbuild/styled-jsx/package.json
- rsbuild/styled-jsx/rsbuild.config.ts
- rsbuild/styled-jsx/src/App.tsx
- rsbuild/styled-jsx/src/env.d.ts
- rsbuild/styled-jsx/src/index.tsx
- rsbuild/styled-jsx/src/stylex.d.ts
- rsbuild/styled-jsx/tsconfig.json
use https://www.npmjs.com/package/@swc/plugin-styled-jsx
> feat: add rsbuild-styled-jsx example

- rsbuild/vue3-auto-import/.vscode/extensions.json
- rsbuild/vue3-element-plus/.vscode/extensions.json
- rsbuild/vue3/.vscode/extensions.json
See: https://github.com/web-infra-dev/rsbuild/pull/1749
> chore: remove vscode-typescript-vue-plugin

- rsbuild/react-compiler-babel/.gitignore
- rsbuild/react-compiler-babel/README.md
- rsbuild/react-compiler-babel/package.json
- rsbuild/react-compiler-babel/rsbuild.config.ts
- rsbuild/react-compiler-babel/src/App.css
- rsbuild/react-compiler-babel/src/App.tsx
- rsbuild/react-compiler-babel/src/env.d.ts
- rsbuild/react-compiler-babel/src/index.tsx
- rsbuild/react-compiler-babel/tsconfig.json
- Doc: https://react.dev/learn/react-compiler
- Plugin: https://www.npmjs.com/package/babel-plugin-react-compiler
> Add example for React Compiler with Rsbuild

- rsbuild/shadcn-ui/.gitignore
- rsbuild/shadcn-ui/README.md
- rsbuild/shadcn-ui/app/globals.css
- rsbuild/shadcn-ui/components.json
- rsbuild/shadcn-ui/package.json
- rsbuild/shadcn-ui/postcss.config.js
- rsbuild/shadcn-ui/rsbuild.config.ts
- rsbuild/shadcn-ui/src/App.tsx
- rsbuild/shadcn-ui/src/components/ui/button.tsx
- rsbuild/shadcn-ui/src/components/ui/card.tsx
- rsbuild/shadcn-ui/src/components/ui/input.tsx
- rsbuild/shadcn-ui/src/components/ui/label.tsx
- rsbuild/shadcn-ui/src/env.d.ts
- rsbuild/shadcn-ui/src/index.tsx
- rsbuild/shadcn-ui/src/lib/utils.ts
- rsbuild/shadcn-ui/tailwind.config.js
- rsbuild/shadcn-ui/tsconfig.json
> feat(rsbuild): add shadcn/ui example

- .github/workflows/check.yaml
run build when pushing to main
> chore(workflow): run build when pushing to main

- rspack/react-compiler-babel/babel.config.js
- rspack/react-compiler-babel/rspack.config.js
improve rspack + React Compiler example:
- create babel.config.js
- update swc-loader options
- add rule for .js file
> feat: improve rspack + React Compiler example

- package.json
- rsdoctor/arco-pro/rspack.config.js
- rspack/basic-ts/rspack.config.js
- rspack/builtin-swc-loader/rspack.config.js
- rspack/cra-ts/rspack.config.js
- rspack/cra/rspack.config.js
- rspack/loader-compat/rspack.config.js
- rspack/postcss-loader/rspack.config.js
- rspack/preact/rspack.config.js
- rspack/react-15-classic/rspack.config.js
- rspack/react-15/rspack.config.js
- rspack/react-compiler-babel/rspack.config.js
- rspack/react-storybook/rspack.config.js
- rspack/react-with-less/rspack.config.js
- rspack/react-with-sass/rspack.config.js
- rspack/react/rspack.config.js
- rspack/solid/rspack.config.js
- rspack/svelte/rspack.config.js
- rspack/tailwind-jit/rspack.config.js
- rspack/tailwind/rspack.config.js
- rspack/treeshaking-transform-imports/rspack.config.js
- rspack/vanilla-extract-css/rspack.config.js
- rspack/vue/rspack.config.js
- rspack/vue2/rspack.config.js
- rspack/vue3-jsx/rspack.config.js
- rspack/vue3-tsx/rspack.config.js
since rspack 1.0.0-alpha, experiments.css is default false.
https://github.com/web-infra-dev/rspack/releases/tag/v1.0.0-alpha.0
> fix: adapt rspack 1.0.0-alpha

- rspack/monaco-editor-ts-react/rspack.config.js
update example for https://github.com/web-infra-dev/rspack/pull/6872
> refactor: remove resolve tsConfigPath

- rsbuild/fastify/server.mjs
- rsbuild/ssr-express/.gitignore
- rsbuild/ssr-express/README.md
- rsbuild/ssr-express/package.json
- rsbuild/ssr-express/rsbuild.config.mjs
- rsbuild/ssr-express/server.mjs
- rsbuild/ssr-express/src/App.css
- rsbuild/ssr-express/src/App.tsx
- rsbuild/ssr-express/src/env.d.ts
- rsbuild/ssr-express/src/index.server.tsx
- rsbuild/ssr-express/src/index.tsx
- rsbuild/ssr-express/template.html
- rsbuild/ssr-express/tsconfig.json
- rsbuild/ssr/package.json
- rsbuild/ssr/rsbuild.config.ts
- rsbuild/ssr/src/App.css
- rsbuild/ssr/src/App.tsx
- rsbuild/ssr/src/env.d.ts
- rsbuild/ssr/src/index.server.tsx
- rsbuild/ssr/src/index.tsx
- rsbuild/ssr/template.html
- rsbuild/ssr/tsconfig.json
https://github.com/web-infra-dev/rsbuild/pull/2528
> feat: add rsbuild ssr example

- package.json
- rspack/rspack-manifest-plugin/package.json
- rspack/rspack-manifest-plugin/test.js
> feat: support test rspack

- .gitignore
- pnpm-lock.yaml
- rsbuild/react-tailwindcss/package.json
- rsbuild/shadcn-ui/package.json
- rsbuild/stylex/package.json
- rsdoctor/modern-minimal/package.json
- rsdoctor/next-minimal/package.json
- rspack/eslint/package.json
- rspack/svelte/package.json
- rspack/vanilla-extract-css/package.json
- rspress/basic/package.json
- rspress/custom-theme/package.json
Fix some peer dependencies warnings
> fix: some peer dependencies warnings

- pnpm-lock.yaml
- rspack/builtin-swc-loader/package.json
- rspack/copy-webpack-plugin@5/package.json
- rspack/fork-ts-checker-webpack-plugin/package.json
- rspack/generate-package-json-webpack-plugin@2/package.json
- rspack/html-webpack-plugin/package.json
- rspack/license-webpack-plugin/package.json
- rspack/nest-alias/package.json
- rspack/rspack-manifest-plugin/package.json
- rspack/webpack-bundle-analyzer/package.json
- rspack/webpack-stats-plugin/package.json
fix missing @rspack/core peer dependency
> fix: missing @rspack/core peer dependency

- .github/workflows/renovate.json5
https://github.com/rspack-contrib/rspack-examples/pull/111
> chore: init renovate config

- pnpm-lock.yaml
- rspack/monaco-editor-js/package.json
- rspack/monaco-editor-js/rspack.config.js
- rspack/monaco-editor-ts-react/package.json
- rspack/monaco-editor-ts-react/rspack.config.js
- rspack/monaco-editor-ts-react/src/index.tsx
- rspack/monaco-editor-webpack-plugin/package.json
- rspack/monaco-editor-webpack-plugin/rspack.config.js
> chore(monaco-editor-ts-react): update monaco-editor-ts-react

- pnpm-lock.yaml
- rsbuild/react-eslint/package.json
- rsbuild/vue3-eslint/package.json
- rsbuild/vue3-eslint/rsbuild.config.ts
- rspack/eslint/package.json
https://github.com/rspack-contrib/eslint-rspack-plugin/pull/4
> fix: use eslint-rspack-plugin instead of eslint-webpack-plugin

- pnpm-lock.yaml
- rspack/preact-refresh/package.json
> chore: update preact refresh to 1.0.0

- .github/renovate.json5
- pnpm-lock.yaml
- rspack/vanilla-extract-css/package.json
- rspack/vanilla-extract-css/rspack.config.js
clean up vanilla-extract-css example, remove unused dependencies.
> fix: clean up vanilla-extract-css example

- pnpm-lock.yaml
- rspack/sentry/index.html
- rspack/sentry/package.json
- rspack/sentry/rspack.config.js
- rspack/sentry/src/answer.js
- rspack/sentry/src/index.js
> feat: add sentry plugin example

- pnpm-lock.yaml
- rspack/hooks/after-resolve/index.html
- rspack/hooks/after-resolve/package.json
- rspack/hooks/after-resolve/rspack.config.js
- rspack/hooks/after-resolve/src/answer.js
- rspack/hooks/after-resolve/src/index.js
add afterReslver hook usage
related to https://discord.com/channels/977448667919286283/1283146907635683389/1283146907635683389
> feat: add afterResolve hook usage

- pnpm-lock.yaml
- rspack/preact-refresh/package.json
- rspack/preact-refresh/rspack.config.js
- use swc plugin in preact-refresh demo
- update @rspack/plugin-preact-refresh to `1.1.0`
> fix: use swc plugin in preact-refresh demo

- rsbuild/ssr-express/src/index.tsx
- rsbuild/ssr/src/index.tsx
use `react.hydrateRoot` API in ssr examples.
https://react.dev/reference/react-dom/client/hydrateRoot
> chore: update SSR example

- pnpm-lock.yaml
- rspack/dll-reference/index.js
- rspack/dll-reference/package.json
- rspack/dll-reference/rspack.config.js
- rspack/dll/a.ts
- rspack/dll/alpha.ts
- rspack/dll/b.ts
- rspack/dll/beta.ts
- rspack/dll/c.tsx
- rspack/dll/package.json
- rspack/dll/rspack.config.js
- Add dll plugin example
- Add dll reference example
> feat: add dll & dll-reference plugin examples

- pnpm-lock.yaml
- rspack/vue3-jsx/package.json
- rspack/vue3-tsx/package.json
resolve https://github.com/rspack-contrib/rspack-examples/issues/163
> fix: vue3-jsx examples are broken

- pnpm-lock.yaml
- rsbuild/module-federation-enhanced/consumer/package.json
- rsbuild/module-federation-enhanced/consumer/rsbuild.config.ts
- rsbuild/module-federation-enhanced/provider/package.json
- rsbuild/module-federation-enhanced/provider/rsbuild.config.ts
- rsbuild/module-federation/remote/rsbuild.config.ts
Update Rsbuild MF examples to use https://module-federation.io/guide/basic/rsbuild.html
> feat: update Rsbuild MF examples

- pnpm-lock.yaml
- rsbuild/react-unocss/package.json
- rsbuild/react-unocss/rsbuild.config.ts
- rsbuild/react-unocss/src/App.tsx
- rsbuild/react-unocss/src/index.css
- rsbuild/react-unocss/src/index.tsx
- rsbuild/react-unocss/src/shim.d.ts
- rsbuild/react-unocss/tsconfig.json
https://github.com/web-infra-dev/rsbuild/issues/4285
> feat: add rsbuild-react-unocss example

- pnpm-lock.yaml
> chore: pnpm dedupe

- rspack/builtin-swc-loader/rspack.config.mjs
- rspack/cra-ts/rspack.config.js
- rspack/cra/rspack.config.js
- rspack/emotion/rspack.config.js
- rspack/extract-license/rspack.config.js
- rspack/loader-compat/rspack.config.js
- rspack/react-refresh-babel-loader/rspack.config.js
- rspack/react-refresh/rspack.config.js
- rspack/react-with-extract-css/rspack.config.js
- rspack/react-with-less/rspack.config.js
- rspack/react-with-sass/rspack.config.js
- rspack/solid/rspack.config.js
- rspack/styled-components/rspack.config.js
- rspack/svgr/rspack.config.js
- rspack/vanilla-extract-css/package.json
- rspack/vanilla-extract-css/src/index.tsx
- rspack/vanilla-extract-css/tsconfig.json
- rspack/vue2-tsx/rspack.config.js
- rspack/vue3-jsx/rspack.config.js
- rspack/vue3-vanilla/rspack.config.js
- fix vanilla-extract example
- remove useless `minimize: false`
> fix: fix vanilla-extract example and remove minimize false

- pnpm-lock.yaml
- rspress/custom-theme/package.json
Fix the broken Rspress custom theme example
> fix: Rspress custom theme example

- package.json
https://github.com/pnpm/pnpm/releases/tag/v10.0.0
> chore(deps): bump pnpm to v10

- pnpm-lock.yaml
- rspack/lazy-compilation-server/dev.js
- rspack/lazy-compilation-server/package.json
- rspack/lazy-compilation-server/src/index.js
- rspack/lazy-compilation-server/src/info.js
- rspack/lazy-compilation-server/src/show-msg.js
add example of how to use custom server for lazy compilation
> feat: add example of lazy compilation using custom server

- rspack/vue2-ts/rspack.config.js
https://github.com/web-infra-dev/rspack/issues/9557
> fix: vue 2 example source map

- pnpm-lock.yaml
- rspack/worker-inline/index.html
- rspack/worker-inline/package.json
- rspack/worker-inline/rspack.config.mjs
- rspack/worker-inline/src/index.js
- rspack/worker-inline/src/worker.js
https://github.com/web-infra-dev/rsbuild/issues/4762
> feat: add worker inline example

- pnpm-lock.yaml
- rspack/http-import/.gitignore
- rspack/http-import/http-import.lock
- rspack/http-import/index.html
- rspack/http-import/package.json
- rspack/http-import/rspack.config.mjs
- rspack/http-import/src/index.js
> feat: add http-import example
